service: clear-lambda-storage
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.10
  versionFunctions: false
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:List*
        - lambda:DeleteFunction
      Resource: "*"

package:
  exclude:
    - .git/**
    - node_modules/**
    - __pycache__/**
    - package-lock.json
    - package.json
    - README.srt

functions:
  clearLambdaStorage:
    handler: handler.clear_lambda_storage
    memorySize: 512
    timeout: 900
    events:
      ## Schedule: Every day at 03:00 Eastern
      - schedule:
          method: scheduler
          rate: cron(0 3 * * ? *)
          timezone: America/New_York

resources:
  Resources:
    ClearLambdaStorageAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: !Sub 'Alarms when the ${AWS::StackName} clear_lambda_storage Lambda errors'
        AlarmName: !Sub '${AWS::StackName}-clear-lambda-storage-alarm'
        AlarmActions:
          - !ImportValue hellotill-platform-alarms-production:IntegrationsLowPriorityAlarmTopicArn
        Namespace: AWS/Lambda
        ComparisonOperator: GreaterThanThreshold
        DatapointsToAlarm: 1
        EvaluationPeriods: 1
        Period: 60
        Statistic: Sum
        Threshold: 0
        TreatMissingData: notBreaching
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref ClearLambdaStorageLambdaFunction