service: clear-lambda-storage

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:ListFunctions
        - lambda:ListVersionsByFunction
        - lambda:DeleteFunction
      Resource: "*"

package:
  exclude:
    - .git/**
    - node_modules/**
    - __pycache__/**
    - package-lock.json
    - package.json
    - README.srt

functions:
  clear_lambda_storage:
    handler: handler.clear_lambda_storage
    memorySize: 128
    timeout: 120
    events:
      ## Schedule: Every other hour
      - schedule:
          method: scheduler
          rate: cron(0 */2 * * ? *)
          timezone: America/New_York

resources:
  Resources:
    ClearLambdaStorageAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: !Sub 'Alarms when the ${AWS::StackName} clear_lambda_storage Lambda errors'
        AlarmName: !Sub '${AWS::StackName}-clear-lambda-storage-alarm'
        AlarmActions:
          - !ImportValue hellotill-platform-alarms-production:IntegrationsLowPriorityAlarmTopicArn
        Namespace: AWS/Lambda
        ComparisonOperator: GreaterThanThreshold
        DatapointsToAlarm: 1
        EvaluationPeriods: 1
        Period: 60
        Statistic: Sum
        Threshold: 0
        TreatMissingData: notBreaching
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref ClearLambdaStorageLambdaFunction
