service: clear-lambda-storage
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.10
  versionFunctions: false
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:List*
        - lambda:DeleteFunction
      Resource: "*"

package:
  exclude:
    - .git/**
    - node_modules/**
    - __pycache__/**
    - package-lock.json
    - package.json
    - README.srt

functions:
  clear_lambda_storage:
    handler: handler.clear_lambda_storage
    memorySize: 512
    timeout: 900
    events:
      ## Schedule: Every day at 03:00 Eastern
      - schedule:
          method: scheduler
          rate: cron(0 3 * * ? *)
          timezone: America/New_York
